flake8:
  image: python:latest
  before_script:
    - apt update
    - pip3 install flake8
  script:
    - flake8 --version
    - flake8 src/
  except:
    - master


pylint:
  image: python:latest
  before_script:
  - apt update && apt install -y bc
  - pip3 install -q pylint
  - PYLINT_THRESHOLD=9.0
  script:
  - pylint --version
  - find src -type f -iname "*.py" ! -iname "__init__.py" | xargs -r pylint --disable=C0111 | tee pylint.txt || true
  - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
  - if [ -z "$score" ]; then score=10.0; fi
  - (( $(bc <<< "$score >= $PYLINT_THRESHOLD") ))
  except:
  - master

tests:
    image: python:latest
    script:
    - python test_runner.py
    except:
    - master
